import Head from "next/head";
import PopularRecipes from "components/recipe/PopularRecipes";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="background text-slate-100">
        <div className="w-full h-full bg-black bg-opacity-70">
          <div className="h-[550px] flex flex-col items-center justify-center mb-10 pb-10">
            <h2 className="text-6xl mb-3 font-bold">
              The best place to find your recipe
            </h2>
            <div>Want to learn cook but confused how to start?</div>
            <div className="mb-3">No need to worry again</div>
            <input
              type="text"
              className="text-slate-800 px-2 py-1 rounded outline-none w-72"
              placeholder="Search for Recipes"
            />
          </div>
        </div>
      </div>
      <PopularRecipes />
    </>
  );
}
