import Head from "next/head";
import { GetStaticProps } from "next";
import { useState } from "react";
import { useRouter } from "next/router";
import PopularRecipes from "components/recipe/PopularRecipes";
import { gql } from "@apollo/client";

import client from "utils/apolloClient";
import { IRecipeCard } from "types/recipe";

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      {
        popularRecipes {
          edges {
            node {
              id
              name
              mainImage
              totalTime
              mealTags
            }
          }
        }
      }
    `,
  });
  const recipes = data.popularRecipes.edges.map((recipe: any) => {
    return {
      id: recipe.node.id,
      name: recipe.node.name,
      mainImage: recipe.node.mainImage,
      totalTime: recipe.node.totalTime,
      mealTags: recipe.node.mealTags,
    };
  });

  return {
    props: {
      recipes,
    },
    revalidate: 60,
  };
};

export default function Home({ recipes }: { recipes: IRecipeCard }) {
  const [textSearch, setTextSearch] = useState("");
  const router = useRouter();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTextSearch(e.target.value);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!textSearch) return;
    router.push(`/search?q=${textSearch}`);
  };
  return (
    <>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="background text-slate-100">
        <div className="w-full h-full bg-black bg-opacity-70">
          <div className="h-[600px] flex flex-col items-center justify-center mb-10 pb-10">
            <h2 className="text-6xl mb-3 font-semibold">
              The best place to find your recipe
            </h2>
            <div>Want to learn cook but confused how to start?</div>
            <div className="mb-3">No need to worry again</div>
            <form onSubmit={handleSubmit}>
              <input
                type="text"
                className="text-slate-800 px-2 py-1 rounded outline-none w-72"
                placeholder="Search for Recipes"
                onChange={handleChange}
              />
            </form>
          </div>
        </div>
      </div>
      <PopularRecipes recipes={recipes} />
    </>
  );
}
